<?php
// Render the real plugin page entrypoints in the browser fixture, including script tags.
$sourceRoot = dirname(__DIR__) . '/src/usr/local/emhttp';
// Model the installed package, whose VERSION file is generated by the builder.
$docroot = sys_get_temp_dir() . '/dg-settings-' . bin2hex(random_bytes(6));
$plugin = '/plugins/deadlock-guard';
mkdir($docroot . $plugin, 0755, true);
copy(dirname(__DIR__) . '/VERSION', $docroot . $plugin . '/VERSION');
foreach (['javascript', 'styles', 'lib'] as $directory) {
    symlink($sourceRoot . $plugin . '/' . $directory, $docroot . $plugin . '/' . $directory);
}
function pageBody(string $name): string
{
    global $sourceRoot;
    return explode(
        "---\n",
        file_get_contents("$sourceRoot/plugins/deadlock-guard/$name.page"),
        2,
    )[1];
}
echo '<!doctype html><html><head><meta charset="utf-8"><title>Deadlock Guard settings fixture</title><style>body{font:14px Arial;background:#202020;color:#ddd;margin:24px}button{padding:8px 12px}</style>';
eval('?>' . pageBody('DeadlockGuardButtons'));
echo '<script>window.DeadlockGuardToken="fixture";</script></head><body>';
eval('?>' . pageBody('DeadlockGuard'));
echo '</body></html>';
