const {test}=require('node:test');const assert=require('node:assert/strict');
let api;try{api=require('../../source/usr/local/emhttp/plugins/deadlock-guard/javascript/integration.js');}catch{}
function fixture(){const calls=[];const win={eventControl(...args){calls.push(['docker',...args]);},ajaxVMDispatch(...args){calls.push(['vm',...args]);},ajaxVMDispatchconsole(...args){calls.push(['console',...args]);},ajaxVMDispatchconsoleRV(...args){calls.push(['rv',...args]);},startAll(){calls.push(['bulk']);},resumeAll(){calls.push(['resumeAll']);},location:{pathname:'/Docker'},loadlist(){calls.push(['refresh']);}};return {win,calls};}
test('managed native start waits for job; unmanaged actions preserve original arguments',async()=>{assert.ok(api,'Integration module missing');const {win,calls}=fixture();const seen=[];
 api.install(win,async b=>{seen.push(b);return {managed:true,job:{id:'job',status:'succeeded'}};},()=>{},async()=>{});
 await win.eventControl({action:'start',container:'abc'},'loadlist');assert.equal(calls.filter(x=>x[0]==='docker').length,0);assert.equal(seen[0].native.id,'abc');
 win.eventControl({action:'stop',container:'abc'},'loadlist');assert.deepEqual(calls.at(-1),['docker',{action:'stop',container:'abc'},'loadlist']);
});
test('unmanaged start goes to original dispatch and API errors never fall through',async()=>{const {win,calls}=fixture();api.install(win,async()=>({managed:false}),()=>{},async()=>{});await win.ajaxVMDispatch({action:'domain-start',uuid:'uuid'},'loadlist');assert.equal(calls[0][0],'vm');
 const second=fixture();const errors=[];api.install(second.win,async()=>{throw Error('offline')},x=>errors.push(x),async()=>{});await second.win.eventControl({action:'start',container:'abc'});assert.equal(second.calls.length,0);assert.match(errors.at(-1),/offline/);
});
test('VM console variants use completed job and never issue a second native start',async()=>{for(const name of ['ajaxVMDispatchconsole','ajaxVMDispatchconsoleRV']){const {win,calls}=fixture();const consoles=[];api.install(win,async()=>({managed:true,requests:[{workload:{type:'vm',id:'uuid'}}],job:{id:'job',status:'succeeded'}}),()=>{},async(m,mode)=>consoles.push([m,mode]));await win[name]({action:name.endsWith('RV')?'domain-start-consoleRV':'domain-start-console',uuid:'uuid'},'loadlist');assert.equal(calls.filter(x=>['console','rv'].includes(x[0])).length,0);assert.equal(consoles.length,1);}});
test('VM restart remains restart, resume and bulk route through coordinator',async()=>{const {win}=fixture();const seen=[];api.install(win,async b=>{seen.push(b);return {managed:false}},()=>{},async()=>{});await win.ajaxVMDispatch({action:'domain-restart',uuid:'uuid'});await win.eventControl({action:'resume',container:'abc'});await win.startAll();await win.resumeAll();assert.deepEqual(seen.map(x=>x.native.action),['restart','resume','start','resume']);assert.equal(seen[2].native.bulk,true);});
test('Dashboard shares dispatch wrappers and installer is idempotent',async()=>{const {win,calls}=fixture();win.location.pathname='/Dashboard';let n=0;const send=async()=>{n++;return {managed:false}};api.install(win,send,()=>{},async()=>{});api.install(win,send,()=>{},async()=>{});await win.eventControl({action:'restart',container:'abc'});assert.equal(n,1);assert.equal(calls.length,1);});
test('duplicate clicks share one accepted handoff',async()=>{const {win}=fixture();let finish;let count=0;api.install(win,()=>{count++;return new Promise(r=>finish=r)},()=>{},async()=>{});const a=win.eventControl({action:'start',container:'abc'});const b=win.eventControl({action:'start',container:'abc'});assert.equal(a,b);finish({managed:true,job:{id:'one',status:'succeeded'}});await a;assert.equal(count,1);});
